name: menasyp
description: A new Flutter project.
publish_to: 'none'
version: 1.1.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  country_icons: ^3.0.0
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  gsheets: ^0.5.0
  http: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.5.0
  path_provider: ^2.1.3
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.3
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto  
      fonts:
        - asset: assets/Roboto.ttf  